export {};

interface Group {
  name: string;
  description: string;
  elements: string[];
  table: number[][];
}

const groupSelect = document.querySelector<HTMLSelectElement>("#group-select");
const normalSelect = document.querySelector<HTMLSelectElement>("#normal-select");
const summaryOutput = document.querySelector<HTMLDivElement>("#group-summary");
const cayleyOutput = document.querySelector<HTMLDivElement>("#cayley-table");
const ordersOutput = document.querySelector<HTMLDivElement>("#element-orders");
const centerOutput = document.querySelector<HTMLDivElement>("#center-output");
const conjugacyOutput = document.querySelector<HTMLDivElement>("#conjugacy-output");
const subgroupsOutput = document.querySelector<HTMLDivElement>("#subgroups-output");
const quotientOutput = document.querySelector<HTMLDivElement>("#quotient-output");

function escapeHtml(text: string): string {
  return text.replace(/[&<>"]/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" })[ch]!);
}

function superscript(n: number): string {
  const digits: Record<string, string> = { "0": "⁰", "1": "¹", "2": "²", "3": "³", "4": "⁴", "5": "⁵", "6": "⁶", "7": "⁷", "8": "⁸", "9": "⁹" };
  return String(n).replace(/\d/g, (d) => digits[d]);
}

function cyclic(n: number): Group {
  const elements = Array.from({ length: n }, (_, i) => i === 0 ? "e" : i === 1 ? "a" : `a${superscript(i)}`);
  return {
    name: `cyclic C${n}`,
    description: `rotations modulo ${n}; generated by a single element a with a${superscript(n)} = e`,
    elements,
    table: Array.from({ length: n }, (_, i) => Array.from({ length: n }, (_unused, j) => (i + j) % n)),
  };
}

function klein(): Group {
  const elements = ["e", "a", "b", "ab"];
  return {
    name: "klein four V₄",
    description: "C₂ × C₂; every non-identity element has order 2",
    elements,
    table: Array.from({ length: 4 }, (_, i) => Array.from({ length: 4 }, (_unused, j) => i ^ j)),
  };
}

function dihedral(n: number): Group {
  const rotations = Array.from({ length: n }, (_, i) => i === 0 ? "e" : i === 1 ? "r" : `r${superscript(i)}`);
  const reflections = Array.from({ length: n }, (_, i) => i === 0 ? "s" : i === 1 ? "sr" : `sr${superscript(i)}`);
  const elements = [...rotations, ...reflections];
  const decode = (x: number) => ({ i: x % n, reflected: x >= n });
  const encode = (i: number, reflected: boolean) => ((i % n) + n) % n + (reflected ? n : 0);

  return {
    name: `dihedral D${n}`,
    description: `symmetries of a regular ${n}-gon; order ${2 * n}, with srs = r⁻¹`,
    elements,
    table: Array.from({ length: 2 * n }, (_, a) => Array.from({ length: 2 * n }, (_unused, b) => {
      const left = decode(a);
      const right = decode(b);
      return encode(left.i + (left.reflected ? -right.i : right.i), left.reflected !== right.reflected);
    })),
  };
}

function symmetricThree(): Group {
  const perms = [
    [0, 1, 2],
    [1, 2, 0],
    [2, 0, 1],
    [1, 0, 2],
    [2, 1, 0],
    [0, 2, 1],
  ];
  const elements = ["e", "(123)", "(132)", "(12)", "(13)", "(23)"];
  const key = (p: number[]) => p.join("");
  const index = new Map(perms.map((p, i) => [key(p), i]));
  return {
    name: "symmetric S₃",
    description: "all permutations of three objects; the smallest non-abelian group",
    elements,
    table: perms.map((p) => perms.map((q) => index.get(key(q.map((x) => p[x])))!)),
  };
}

function quaternion(): Group {
  const elements = ["1", "-1", "i", "-i", "j", "-j", "k", "-k"];
  const index = new Map(elements.map((name, i) => [name, i]));
  const base: Record<string, Record<string, [number, string]>> = {
    "1": { "1": [1, "1"], i: [1, "i"], j: [1, "j"], k: [1, "k"] },
    i: { "1": [1, "i"], i: [-1, "1"], j: [1, "k"], k: [-1, "j"] },
    j: { "1": [1, "j"], i: [-1, "k"], j: [-1, "1"], k: [1, "i"] },
    k: { "1": [1, "k"], i: [1, "j"], j: [-1, "i"], k: [-1, "1"] },
  };
  const parse = (name: string) => ({ sign: name.startsWith("-") ? -1 : 1, unit: name.replace("-", "") });
  const multiply = (a: string, b: string): string => {
    const left = parse(a);
    const right = parse(b);
    const [sign, unit] = base[left.unit][right.unit];
    const resultSign = left.sign * right.sign * sign;
    return resultSign < 0 && unit !== "1" ? `-${unit}` : resultSign < 0 ? "-1" : unit;
  };

  return {
    name: "quaternion Q₈",
    description: "non-abelian group {±1, ±i, ±j, ±k} with i² = j² = k² = ijk = -1",
    elements,
    table: elements.map((a) => elements.map((b) => index.get(multiply(a, b))!)),
  };
}

function makeGroup(id: string): Group {
  if (/^C\d+$/.test(id)) return cyclic(Number(id.slice(1)));
  if (/^D\d+$/.test(id)) return dihedral(Number(id.slice(1)));
  if (id === "V4") return klein();
  if (id === "S3") return symmetricThree();
  if (id === "Q8") return quaternion();
  return dihedral(4);
}

function inverse(group: Group, a: number): number {
  return group.table[a].findIndex((x) => x === 0);
}

function elementOrder(group: Group, a: number): number {
  let product = 0;
  for (let n = 1; n <= group.elements.length; n++) {
    product = group.table[product][a];
    if (product === 0) return n;
  }
  return 0;
}

function setKey(set: number[]): string {
  return [...set].sort((a, b) => a - b).join(",");
}

function formatSet(group: Group, set: number[]): string {
  return `{ ${[...set].sort((a, b) => a - b).map((x) => escapeHtml(group.elements[x])).join(", ")} }`;
}

function isSubgroup(group: Group, set: number[]): boolean {
  if (!set.includes(0)) return false;
  const members = new Set(set);
  return set.every((a) => members.has(inverse(group, a)) && set.every((b) => members.has(group.table[a][b])));
}

function isNormal(group: Group, subgroup: number[]): boolean {
  const members = new Set(subgroup);
  return group.elements.every((_name, g) => {
    const gInv = inverse(group, g);
    return subgroup.every((h) => members.has(group.table[group.table[g][h]][gInv]));
  });
}

function allSubgroups(group: Group): number[][] {
  const n = group.elements.length;
  const result: number[][] = [];
  for (let mask = 1; mask < 2 ** n; mask++) {
    if ((mask & 1) === 0) continue;
    const set = Array.from({ length: n }, (_unused, i) => i).filter((i) => (mask & (1 << i)) !== 0);
    if (isSubgroup(group, set)) result.push(set);
  }
  return result.sort((a, b) => a.length - b.length || setKey(a).localeCompare(setKey(b)));
}

function center(group: Group): number[] {
  return group.elements.map((_name, i) => i).filter((a) => group.elements.every((_other, b) => group.table[a][b] === group.table[b][a]));
}

function conjugacyClasses(group: Group): number[][] {
  const seen = new Set<number>();
  const classes: number[][] = [];
  group.elements.forEach((_name, a) => {
    if (seen.has(a)) return;
    const cls = new Set<number>();
    group.elements.forEach((_gName, g) => cls.add(group.table[group.table[g][a]][inverse(group, g)]));
    const sorted = [...cls].sort((x, y) => x - y);
    sorted.forEach((x) => seen.add(x));
    classes.push(sorted);
  });
  return classes;
}

function renderTable(group: Group, table: number[][], labels = group.elements): string {
  const header = `<tr><th>·</th>${labels.map((label) => `<th>${escapeHtml(label)}</th>`).join("")}</tr>`;
  const rows = table.map((row, i) => `<tr><th>${escapeHtml(labels[i])}</th>${row.map((cell) => `<td>${escapeHtml(labels[cell])}</td>`).join("")}</tr>`).join("");
  return `<table class="group-table">${header}${rows}</table>`;
}

function cosets(group: Group, subgroup: number[]): number[][] {
  const seen = new Set<number>();
  const result: number[][] = [];
  group.elements.forEach((_name, g) => {
    if (seen.has(g)) return;
    const coset = [...new Set(subgroup.map((h) => group.table[g][h]))].sort((a, b) => a - b);
    coset.forEach((x) => seen.add(x));
    result.push(coset);
  });
  return result;
}

function renderQuotient(group: Group, subgroup: number[]) {
  if (!quotientOutput) return;
  const groupCosets = cosets(group, subgroup);
  const labels = groupCosets.map((coset) => formatSet(group, coset).replace(/[{} ]/g, "") || "H");
  const cosetIndex = new Map<number, number>();
  groupCosets.forEach((coset, i) => coset.forEach((x) => cosetIndex.set(x, i)));
  const quotientTable = groupCosets.map((a) => groupCosets.map((b) => cosetIndex.get(group.table[a[0]][b[0]])!));
  quotientOutput.innerHTML = `
    <p class="group-muted">${groupCosets.length} cosets of ${formatSet(group, subgroup)}:</p>
    <p>${groupCosets.map((c) => `<span class="group-chip">${formatSet(group, c)}</span>`).join(" ")}</p>
    <div class="group-table-wrap">${renderTable(group, quotientTable, labels)}</div>
  `;
}

function render() {
  if (!groupSelect || !normalSelect || !summaryOutput || !cayleyOutput || !ordersOutput || !centerOutput || !conjugacyOutput || !subgroupsOutput) return;

  const group = makeGroup(groupSelect.value);
  const subgroups = allSubgroups(group);
  const normalSubgroups = subgroups.filter((subgroup) => isNormal(group, subgroup));
  const previousNormal = normalSelect.value;

  normalSelect.innerHTML = normalSubgroups.map((subgroup, i) => `<option value="${i}">${formatSet(group, subgroup)}</option>`).join("");
  normalSelect.value = normalSubgroups[Number(previousNormal)] ? previousNormal : "0";

  summaryOutput.innerHTML = `<strong>${escapeHtml(group.name)}</strong> · order ${group.elements.length} · ${escapeHtml(group.description)}`;
  cayleyOutput.innerHTML = renderTable(group, group.table);
  ordersOutput.innerHTML = `<ol class="group-list">${group.elements.map((name, i) => `<li>${escapeHtml(name)} has order ${elementOrder(group, i)}</li>`).join("")}</ol>`;
  centerOutput.innerHTML = formatSet(group, center(group));
  conjugacyOutput.innerHTML = `<ol class="group-list">${conjugacyClasses(group).map((cls) => `<li>${formatSet(group, cls)}</li>`).join("")}</ol>`;
  subgroupsOutput.innerHTML = `<ol class="group-list">${subgroups.map((subgroup) => `<li>${formatSet(group, subgroup)} <span class="group-muted">order ${subgroup.length}${isNormal(group, subgroup) ? ", normal" : ""}</span></li>`).join("")}</ol>`;
  renderQuotient(group, normalSubgroups[Number(normalSelect.value)] ?? normalSubgroups[0]);
}

groupSelect?.addEventListener("change", render);
normalSelect?.addEventListener("change", render);
render();
